swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contient tous les points de terminaison disponibles dans cette base de code
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Connexion
      description: API pour la connexion
      parameters:
        - in: body
          name: body
          description: Payload de connexion
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Connexion réussie
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /user/signup:
    post:
      tags:
        - User Module
      summary: Inscription
      description: API pour l'inscription
      parameters:
        - in: body
          name: body
          description: Payload d'inscription
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Inscription réussie
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: API du profil utilisateur
      description: API pour récupérer le profil d'un utilisateur
      responses:
        '200':
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: API du profil utilisateur
      description: API pour mettre à jour un profil utilisateur
      parameters:
        - in: body
          name: body
          description: Mettre à jour les attributs du profil utilisateur
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: Profil utilisateur mis à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '500':
          description: Erreur interne du serveur
  /user/account:
    get:
      tags:
        - Accounts and Transactions Module
      summary: Tous les comptes
      description: API pour récupérer tous les comptes utilisateur
      security:
        - Bearer: []
      responses: 
        '200':
          description: Tous les comptes récupérés avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountResponse'
        '401':
          description: Utilisateur non autorisé
        '500':
          description: Erreur interne du serveur
  /account/{accountID}/transactions:
    get:
      tags:
        - Accounts and Transactions Module
      summary: Transactions du compte
      description: API pour récupérer la liste des transactions associées à un compte
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: accountID
          description: ID d'un compte
          required: true
          type: string
      responses:
        '200':
          description: Toutes les transactions récupérées avec succès
          schema: 
            type: array
            items:
              $ref: '#/definitions/TransactionsResponse'
        '401':
          description: Utilisateur non autorisé
        '404': 
          description: Compte non trouvé
        '500':
          description: Erreur interne du serveur
  /transactions/{transactionID}/category:
    patch:
      tags:
        - Accounts and Transactions Module
      summary: Mettre à jour la catégorie de la transaction
      description: API pour mettre à jour la catégorie d'une transaction
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID d'une transaction
          required: true
          type: string
        - in: body
          name: category
          description: Catégorie modifiée de la transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionCategory'
      responses:
        '200':
          description: Catégorie de la transaction modifiée avec succès
          schema: 
            $ref: '#/definitions/TransactionCategory'
        '401': 
          description: Utilisateur non autorisé
        '404': 
          description: Transaction non trouvée
        '500': 
          description: Erreur interne du serveur
  /transactions/{transactionID}/note:
    post:
      tags:
        - Accounts and Transactions Module
      summary: Ajouter une note à la transaction
      description: API pour ajouter une note à une transaction
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID d'une transaction
          required: true
          type: string
        - in: body
          name: note
          description: Nouvelle note de la transaction
          required: true
          schema: 
            $ref: '#/definitions/TransactionNote'
      responses:
        '200':
          description: Note ajoutée à la transaction avec succès
          schema: 
            $ref: '#/definitions/TransactionResponseNote'
        '401':
          description: Utilisateur non autorisé
        '404':
          description: Note non créée
        '500':
          description: Erreur interne du serveur
  /transactions/{transactionID}/note/{noteID}:
    patch:
      tags:
        - Accounts and Transactions Module
      summary: Modifier la note de la transaction
      description: API pour modifier une note d'une transaction
      security: 
        - Bearer: []
      parameters:
        - in: path
          name: transactionID
          description: ID d'une transaction
          required: true
          type: string
        - in: path
          name: noteID
          description: ID d'une note
          required: true
          type: string
        - in: body
          name: note
          description: Modifier la note de la transaction
          required: true
          schema: 
